version: "3.7"

services:
  ignite_rentx_database:
    image: postgres
    container_name: ignite_rentx_database
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: ignite
      POSTGRES_DB: rentx
    volumes:
      - pgdata:/data/postgres
    networks:
      - rentx_lan
  ignite_rentx:
    build: .
    container_name: ignite_rentx
    ports:
      - "3333:3333"
      - "3339:3339"
    volumes:
      - .:/usr/app
    environment:
      - "DATABSE_URL=postgres://docker:ignite@ignite_rentx_database:5432/rentx"
    depends_on:
      - ignite_rentx_database
    networks:
      - rentx_lan

volumes:
  pgdata:
    driver: local

networks:
  rentx_lan: {}
