# A instrução version indica qual versão do docker-compose será utilizada.
version: "3.7"

# A instrução services indica quais serviços serão utilizados.
services:

  # A instrução db é o nome do serviço.
  rentx:

    # A instrução build indica qual será a imagem que será utilizada para a criação do container do serviço. Nesse caso, estamos utilizando a imagem rentx.
    build: .

    # A instrução container_name indica qual será o nome do container do serviço.
    container_name: rentx

    # A instrução ports indica quais portas serão expostas do container do serviço.
    ports:
      - "3333:3333"
      - "3339:3339"

    # A instrução volumes indica quais volumes serão utilizados do container do serviço.
    volumes:
      - .:/usr/app
